# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False, verbose_name='auth.User')),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_address', models.TextField(max_length=50)),
                ('emp_contact', models.CharField(max_length=15)),
                ('emp_alt_contact', models.CharField(max_length=15)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=7)),
                ('emp_dob', models.DateTimeField()),
                ('emp_pan_id', models.CharField(max_length=15)),
                ('emp_aadhar_no', models.CharField(max_length=15)),
                ('emp_profile_pic', models.BinaryField()),
                ('emp_tax_status', models.CharField(choices=[('nri', 'NRI'), ('resident', 'RESIDENT'), ('expat', 'EXPAT')], max_length=10)),
                ('emp_total_leave', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
