# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('mark', models.IntegerField(choices=[(0, 'Absent'), (0.5, 'Half day'), (1, 'Present')])),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=15)),
                ('alt_contact', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('dob', models.DateField()),
                ('pan_id', models.CharField(max_length=15, null=True)),
                ('aadhar_no', models.CharField(max_length=15)),
                ('profile_pic', models.BinaryField()),
                ('tax_status', models.CharField(choices=[('nri', 'NRI'), ('resident', 'RESIDENT'), ('expat', 'EXPAT')], max_length=10)),
                ('total_leave', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Employee'),
        ),
    ]
