# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-17 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='basic_amount',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='gross_deduction',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='gross_earning',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='hra_amount',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='loss_of_pay',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='net_salary',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='paid_days',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='public_holidays',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='total_days',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='weekly_off',
        ),
    ]
