# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_dob',
            field=models.DateField(),
        ),
    ]
