# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-17 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20180517_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='basic_salary_per',
            new_name='basic_salary_perc',
        ),
        migrations.RenameField(
            model_name='salary',
            old_name='hra_per',
            new_name='hra_perc',
        ),
    ]
