# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20180306_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='mark',
            field=models.FloatField(choices=[(0, 'Absent'), (0.5, 'Half day'), (1, 'Present')]),
        ),
    ]
