# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20180305_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_date', models.DateField()),
                ('att_mark', models.IntegerField(choices=[(0, 'Absent'), (0.5, 'Half day'), (1, 'Present')], max_length=3)),
            ],
        ),
    ]
