# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20180306_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='no_of_leaves',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='no_of_present_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
