# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-17 10:02
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20180517_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='gross_month_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0E-10'), max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='income_tax_perc',
            field=models.FloatField(default=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='salary',
            name='prof_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0E-10'), max_digits=10),
        ),
    ]
