# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_auto_20180522_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryhistory',
            old_name='basic_salary_per',
            new_name='basic_perc',
        ),
        migrations.RenameField(
            model_name='salaryhistory',
            old_name='hra_per',
            new_name='hra_perc',
        ),
    ]
