# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 11:00
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_auto_20180522_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryhistory',
            name='basic',
            field=models.DecimalField(decimal_places=2, default=Decimal('0E-10'), max_digits=10),
        ),
        migrations.AddField(
            model_name='salaryhistory',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0E-10'), max_digits=10),
        ),
        migrations.AddField(
            model_name='salaryhistory',
            name='leaves',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salaryhistory',
            name='lop_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salaryhistory',
            name='month_year',
            field=models.CharField(default='', max_length=10),
        ),
    ]
