# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 11:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_auto_20180522_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryhistory',
            name='income_tax_perc',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='basic_perc',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='hra_perc',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
