# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='fax',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
