# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-17 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(max_length=150),
        ),
    ]
