# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-18 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180417_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='namec',
        ),
    ]
