# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180314_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
