# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-03 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20180314_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='address_line1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address_line2',
        ),
    ]
