# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-16 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20180418_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktype',
            name='work_type',
            field=models.CharField(choices=[('SunHol', 'Sunday Holiday'), ('SatSunHol', 'Sat-Sun Holiday')], max_length=20),
        ),
    ]
