# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-23 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180423_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenthistory',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Department'),
        ),
        migrations.AlterField(
            model_name='jobtypehistory',
            name='job_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.JobType'),
        ),
    ]
