# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20180314_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, default='none/no_profile.png', null=True, upload_to='user_profiles/'),
        ),
    ]
