# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-13 05:43
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20180423_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salaryemp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0E-10'), max_digits=10),
        ),
    ]
