# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-13 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_employee_salaryemp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salaryemp',
        ),
    ]
