# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-03 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mark', models.FloatField(choices=[(0, 'Absent'), (0.5, 'Half day'), (1, 'Present')])),
                ('rem_privilege_leave', models.PositiveSmallIntegerField(default=0)),
                ('rem_casual_leave', models.PositiveSmallIntegerField(default=0)),
                ('leave_type', models.CharField(default='---', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_from', models.DateField()),
                ('leave_to', models.DateField()),
                ('leave_type', models.CharField(max_length=20)),
            ],
        ),
    ]
