# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-24 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20180413_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='mark',
            field=models.FloatField(choices=[(0, 'Absent'), (1, 'Present')]),
        ),
    ]
