# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-25 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20180424_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='leave_type',
            field=models.CharField(choices=[('Privilege Leave', 'Privilege Leave'), ('Casual Leave', 'Casual Leave')], max_length=20, null=True),
        ),
    ]
